const ADD_CONTACT_ITEM = 'contacts/ADD_CONTACT_ITEM';
const GET_CONTACT_ITEM = 'contacts/GET_CONTACT_ITEM';
const UPDATE_CONTACT_ITEM = 'contacts/UPDATE_CONTACT_ITEM';
const DELETE_CONTACT_ITEM = 'contacts/DELETE_CONTACT_ITEM';
const GET_CONTACT_LIST = 'contacts/GET_CONTACT_LIST';

export {
    ADD_CONTACT_ITEM,
    GET_CONTACT_ITEM,
    UPDATE_CONTACT_ITEM,
    DELETE_CONTACT_ITEM,
    GET_CONTACT_LIST
}
